---

- name: Create logstash group
  group:
    name: "{{ logstash_group }}"
    state: present

- name: Create logstash user
  user:
    name: "{{ logstash_user }}"
    state: present

- name: Check if Logstash is installed
  stat:
    path: "{{ logstash_install_dir }}"
    follow: yes
  register: logstash_is_installed

- name: Download Logstash archive
  become: yes
  get_url:
    url: "https://artifacts.elastic.co/downloads/logstash/logstash-{{ logstash_version }}.tar.gz"
    dest: "/tmp/logstash-{{ logstash_version }}.tar.gz"
    group: "{{ logstash_group }}"
    owner: "{{ logstash_user }}"
  when: logstash_is_installed.stat.exists == False

- name: Unarchive Logstash
  become: yes
  command: "tar xzvf logstash-{{ logstash_version }}.tar.gz"
  args:
    chdir: /tmp
    creates: "/tmp/logstash-{{ logstash_version }}"
  when: logstash_is_installed.stat.exists == False

- name: Move to install path
  become: yes
  command: "mv logstash-{{ logstash_version }} {{ logstash_install_dir }}-{{ logstash_version }}"
  args:
    chdir: /tmp
    creates: "{{ logstash_install_dir }}-{{ logstash_version }}"
  when: logstash_is_installed.stat.exists == False

- name: Set folder permissions
  file:
    path: "{{ logstash_install_dir }}-{{ logstash_version }}"
    state: directory
    group: "{{ logstash_group }}"
    owner: "{{ logstash_user }}"
    recurse: yes

- name: Create symbolic link
  file:
    src: "{{ logstash_install_dir }}-{{ logstash_version }}"
    dest: "{{ logstash_install_dir }}"
    state: link
  when: logstash_is_installed.stat.exists == False

- name: Create startup file
  become: yes
  template:
    src: startup.options.j2
    dest: "{{ logstash_install_dir }}/config/startup.options"
    backup: yes

- name: Create log directory
  become: yes
  file:
    path: "{{ logstash_path_logs }}"
    state: directory
    group: "{{ logstash_group }}"
    owner: "{{ logstash_user }}"

- name: Create data directory
  become: yes
  file:
    path: "{{ logstash_path_data }}"
    state: directory
    group: "{{ logstash_group }}"
    owner: "{{ logstash_user }}"

- name: Create run directory
  become: yes
  file:
    path: /var/run/logstash
    state: directory
    group: "{{ logstash_group }}"
    owner: "{{ logstash_user }}"

- name: Install HAVEGED
  become: yes
  apt:
    name: haveged
    state: present

- name: Execute system-install
  command: "{{ logstash_install_dir }}/bin/system-install"

- name: Update systemd
  become: yes
  systemd:
    name: logstash
    daemon_reload: yes

- name: Start Logstash
  service:
    name: logstash
    state: started
    enabled: yes