---

- name: Create logstash group
  group:
    name: "{{ logstash_group }}"
    state: present

- name: Create logstash user
  user:
    name: "{{ logstash_user }}"
    state: present

- name: Check if Logstash is installed
  stat:
    path: "{{ logstash_install_dir }}logstash"
    follow: yes
  register: logstash_is_installed

- name: Download Logstash archive
  become: yes
  get_url:
    url: "https://artifacts.elastic.co/downloads/logstash/logstash-{{ logstash_version }}.tar.gz"
    dest: "/tmp/logstash-{{ logstash_version }}.tar.gz"
    group: "{{ logstash_group }}"
    owner: "{{ logstash_user }}"
  when: logstash_is_installed.stat.exists == False

- name: Unarchive Logstash
  become: yes
  command: "tar xzvf logstash-{{ logstash_version }}.tar.gz"
  args:
    chdir: /tmp
    creates: "/tmp/logstash-{{ logstash_version }}"
  when: logstash_is_installed.stat.exists == False

- name: Move to install path
  become: yes
  command: "mv logstash-{{ logstash_version }} {{ logstash_install_dir }}logstash-{{ logstash_version }}"
  args:
    chdir: /tmp
    creates: "{{ logstash_install_dir }}logstash-{{ logstash_version }}"
  when: logstash_is_installed.stat.exists == False

- name: Set folder permissions
  file:
    path: "{{ logstash_install_dir }}logstash-{{ logstash_version }}"
    state: directory
    group: "{{ logstash_group }}"
    owner: "{{ logstash_user }}"
    recurse: yes

- name: Create symbolic link
  file:
    src: "{{ logstash_install_dir }}logstash-{{ logstash_version }}"
    dest: "{{ logstash_install_dir }}logstash"
    state: link
  when: logstash_is_installed.stat.exists == False

- name: Create default file
  template:
    src: ../templates/logstash.environment.j2
    dest: /etc/default/logstash

#- name: Create init script
#  become: yes
#  template:
#    src: ../templates/init.Debian
#    dest: /etc/init.d/logstash
#    mode: 0755
#
#- name: Create service file
#  become: yes
#  template:
#    src: ../templates/logstash.service
#    dest: /lib/systemd/system/logstash.service
#    mode: 0750

- name: Create log directory
  become: yes
  file:
    path: "{{ logstash_log_dir }}"
    state: directory
    group: "{{ logstash_group }}"
    owner: "{{ logstash_user }}"

- name: Create data directory
  become: yes
  file:
    path: "{{ logstash_data_dir }}"
    state: directory
    group: "{{ logstash_group }}"
    owner: "{{ logstash_user }}"

- name: Create run directory
  become: yes
  file:
    path: /var/run/logstash
    state: directory
    group: "{{ logstash_group }}"
    owner: "{{ logstash_user }}"

- name: Execute system-install
  command: "{{ logstash_install_dir }}logstash/bin/system-install"

- name: Update systemd
  become: yes
  systemd:
    name: logstash
    daemon_reload: yes

- name: Configure Logstash
  template:
    src: logstash.yml.j2
    dest: "{{ logstash_install_dir }}logstash/config/logstash.yml"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_user }}"
    backup: yes
    mode: 0750
  notify: restart logstash

- name: Start Logstash
  service:
    name: logstash
    state: started
    enabled: yes